### ISSUE TITLE
diagnostic-channel-publishers - RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Lenoil86** [microsoft/node-diagnostic-channel#101]
Hello.

Few days ago, we upgraded our Node project from diagnostic-channel-publishers v1.0.1 to v1.0.2.

And since this upgrade, after few hours of run, this error occured :

_RangeError: Maximum call stack size exceeded\n at Tracer.tracer.startSpan (/home/vcap/deps/0/node_modules/diagnostic-channel-publishers/dist/src/azure-coretracing.pub.js:57:54)\n at Tracer.tracer.startSpan (/home/vcap/deps/0/node_modules/diagnostic-channel-publishers/dist/src/azure-coretracing.pub.js:57:54)\n at Tracer.tracer.startSpan (/home/vcap/deps/0/node_modules/diagnostic-channel-publishers/dist/src/azure-coretracing.pub.js:57:54)\n at Tracer.tracer.startSpan (/home/vcap/deps/0/node_modules/diagnostic-channel-publishers/dist/src/azure-coretracing.pub.js:57:54)\n at Tracer.tracer.startSpan (/home/vcap/deps/0/node_modules/diagnostic-channel-publishers/dist/src/azure-coretracing.pub.js:57:54)\n at Tracer.tracer.startSpan (/home/vcap/deps/0/node_modules/diagnostic-channel-publishers/dist/src/azure-coretracing.pub.js:57:54)\n at Tracer.tracer.startSpan (/home/vcap/deps/0/node_modules/diagnostic-channel-publishers/dist/src/azure-coretracing.pub.js:57:54)\n at Tracer.tracer.startSpan (/home/vcap/deps/0/node_modules/diagnostic-channel-publishers/dist/src/azure-coretracing.pub.js:57:54)\n at Tracer.tracer.startSpan (/home/vcap/deps/0/node_modules/diagnostic-channel-publishers/dist/src/azure-coretracing.pub.js:57:54)\n at Tracer.tracer.startSpan (/home/vcap/deps/0/node_modules/diagnostic-channel-publishers/dist/src/azure-coretracing.pub.js:57:54)\n at Tracer.tracer.startSpan (/home/vcap/deps/0/node_modules/diagnostic-channel-publishers/dist/src/azure-coretracing.pub.js:57:54)\n at Tracer.tracer.startSpan (/home/vcap/deps/0/node_modules/diagnostic-channel-publishers/dist/src/azure-coretracing.pub.js:57:54)\n at Tracer.tracer.startSpan (/home/vcap/deps/0/node_modules/diagnostic-channel-publishers/dist/src/azure-coretracing.pub.js:57:54)\n at Tracer.tracer.startSpan (/home/vcap/deps/0/node_modules/diagnostic-channel-publishers/dist/src/azure-coretracing.pub.js:57:54)\n at Tracer.tracer.startSpan (/home/vcap/deps/0/node_modules/diagnostic-channel-publishers/dist/src/azure-coretracing.pub.js:57:54)\n at Tracer.tracer.startSpan (/home/vcap/deps/0/node_modules/diagnostic-channel-publishers/dist/src/azure-coretracing.pub.js:57:54)_

I saw the last update of "azure-coretracing.pub" file which manage "@azure/core-tracing" version.
And in our project, we are in 1.0.0-preview.13 version.

Can you please help us ?

FYI, we are downgrading to 1.0.1.

**Comment by Lenoil86** [comment]
Hello,

after a day since we downgraded to 1.0.1, I can confirm that it is all right now.

**Comment by Lenoil86** [comment]
Hello,

issue seems to be fixed now after some days of run without any bug.
I close it.
