### ISSUE TITLE
diagnostic-channel-publishers to support PgQueryStream

### ISSUE THREAD

**Issue by TranHung92** [microsoft/node-diagnostic-channel#67]
I've got this error when executing a query stream
```
TypeError: queryResult.then is not a function
    at Client.query (star-wars/node_modules/diagnostic-channel-publishers/dist/src/pg.pub.js:238:10)
    at PostgresQueryRunner.<anonymous> (star-wars/node_modules/typeorm/build/src/driver/postgres/PostgresQueryRunner.js:218:53)
    at step (star-wars/node_modules/typeorm/node_modules/tslib/tslib.js:136:27)
    at Object.next (star-wars/node_modules/typeorm/node_modules/tslib/tslib.js:117:57)
    at fulfilled (star-wars/node_modules/typeorm/node_modules/tslib/tslib.js:107:62)
```
This occurs when I import `applicationinsights` module without even setup and start app insight

**Comment by imzacm** [comment]
I've got this same issue with pg-cursor, I would appreciate either a fix, or if someone can tell me to disable the pg patching (but keep all other functionality)

**Comment by markwolff** [comment]
You can disable patching for a module via environment variable
```
APPLICATION_INSIGHTS_NO_PATCH_MODULES=pg
```

**Comment by imzacm** [comment]
Thank you, I couldn't see that documented anywhere.
Is there any plan to add support for pg-cursor? Or will I have to permanently disable patching pg?

Either way I'm glad I've got a solution, it'll just be good to know :)

**Comment by luciferankon** [comment]
Hi is there any updates to this? We have intermittently turned off the patching but that's causing our pg logs also not showing up in the App insights. Is there a Permanent solution planned? @markwolff I see the PR is also not merged yet.
